apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zmle347g9-nodejs 
  janus-idp.io/tekton: zmle347g9-nodejs
  backstage.io/kubernetes-id: zmle347g9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zmle347g9-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml